version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - mongo-prod:/data/db
    env_file:
      - ./config/production.evn
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.production
    ports:
      - "80:80"
    env_file:
      - ./config/production.evn
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.production
    ports:
      - "5000:5000"
    env_file:
      - ./config/production.evn
    depends_on:
      - mongodb
volumes:
  mongo-prod:
    driver: local